#!/usr/bin/env python3
"""
Game Engine-Aware Hybrid Quantization Tool

Implements the differentiated quantization strategy used by LongShu:
1. Compute importance matrix (Imatrix) using game development calibration data
2. Classify experts by activation patterns
3. Apply differentiated quantization levels

Usage:
    python quantize_game_aware.py \
        --input-model ./original-model/ \
        --calibration-data ./game_code_corpus/ \
        --output ./quantized-model.gguf

Note: This is a reference implementation. Full quantization requires
the llama.cpp toolchain and access to the original model weights.
"""

import argparse
import json
import os
import sys
from pathlib import Path
from dataclasses import dataclass


@dataclass
class QuantizationConfig:
    """Configuration for differentiated quantization."""
    core_experts: int = 20          # Top experts to preserve
    core_quant: str = "Q5_K_M"      # Quantization for core experts
    standard_quant: str = "IQ3_S"   # Quantization for standard experts
    peripheral_quant: str = "IQ2_XXS"  # Quantization for peripheral experts
    full_attention_quant: str = "Q5_K_M"  # Full attention layer quant
    linear_attention_quant: str = "IQ3_S"  # Linear attention layer quant


def scan_calibration_data(data_dir: str) -> list:
    """Scan calibration data directory and collect file paths."""
    data_path = Path(data_dir)
    if not data_path.exists():
        print(f"Warning: Calibration data directory not found: {data_dir}")
        print("Using default file list for demonstration.")
        return [
            "sample_ue_cpp.cpp",
            "sample_unity_cs.cs",
            "sample_lua.lua",
        ]

    extensions = {'.cpp', '.h', '.cs', '.lua', '.shader', '.hlsl', '.glsl', '.json', '.yaml'}
    files = []
    for ext in extensions:
        files.extend(list(data_path.rglob(f"*{ext}")))
    return [str(f) for f in files[:100]]  # Limit to first 100 files


def compute_importance_scores(files: list) -> dict:
    """
    Compute simplified importance scores for experts.

    In production, this runs the calibration corpus through the model
    and records per-expert activation patterns.

    Returns: {expert_id: importance_score}
    """
    # Simulated importance computation
    # In reality, this uses the Imatrix algorithm from llama.cpp
    print("  Computing importance matrix (Imatrix)...")
    print(f"  Calibration files: {len(files)}")
    print("  (This is a reference implementation — full Imatrix computation")
    print("   requires running the calibration corpus through the model.)")

    # Simulated scores — in production, these come from actual activation tracking
    scores = {}
    for i in range(105):  # 105 experts in Qwen3.5-MoE
        # Simulate that experts 0-19 are core (code/architecture)
        # experts 20-54 are standard, 55-104 are peripheral
        if i < 20:
            scores[i] = 0.85 + (0.15 * (1 - i / 20))  # High scores
        elif i < 55:
            scores[i] = 0.5 + (0.35 * (1 - (i - 20) / 35))  # Medium scores
        else:
            scores[i] = 0.1 + (0.4 * (1 - (i - 55) / 50))  # Low scores

    return scores


def classify_experts(scores: dict, config: QuantizationConfig) -> dict:
    """Classify experts into core/standard/peripheral groups."""
    sorted_experts = sorted(scores.items(), key=lambda x: x[1], reverse=True)

    classification = {
        "core": [],
        "standard": [],
        "peripheral": [],
    }

    for idx, (expert_id, score) in enumerate(sorted_experts):
        if idx < config.core_experts:
            classification["core"].append({
                "id": expert_id,
                "score": round(score, 4),
                "quant_level": config.core_quant,
            })
        elif idx < config.core_experts + 35:
            classification["standard"].append({
                "id": expert_id,
                "score": round(score, 4),
                "quant_level": config.standard_quant,
            })
        else:
            classification["peripheral"].append({
                "id": expert_id,
                "score": round(score, 4),
                "quant_level": config.peripheral_quant,
            })

    return classification


def generate_quantization_script(classification: dict, config: QuantizationConfig) -> str:
    """Generate a llama.cpp quantization command script."""
    script_lines = [
        "#!/bin/bash",
        "# Auto-generated quantization script",
        f"# Generated by LongShu quantize_game_aware.py",
        "",
        'echo "🐉 LongShu Differentiated Quantization"',
        'echo "======================================"',
        "",
        "# Step 1: Quantize core experts (high precision)",
        f'echo "Step 1: Quantizing {len(classification["core"])} core experts with {config.core_quant}..."',
        f"# llama.cpp command for core experts",
        "",
        "# Step 2: Quantize standard experts",
        f'echo "Step 2: Quantizing {len(classification["standard"])} standard experts with {config.standard_quant}..."',
        "",
        "# Step 3: Quantize peripheral experts (aggressive)",
        f'echo "Step 3: Quantizing {len(classification["peripheral"])} peripheral experts with {config.peripheral_quant}..."',
        "",
        "# Step 4: Merge and produce final GGUF",
        'echo "✅ Quantization complete."',
    ]
    return "\n".join(script_lines)


def run_quantization(args):
    """Main quantization pipeline."""
    print("🐉 LongShu Game Engine-Aware Quantization Tool")
    print("=" * 50)

    config = QuantizationConfig()

    # Step 1: Scan calibration data
    print("\n📂 Step 1: Scanning calibration data...")
    files = scan_calibration_data(args.calibration_data)

    # Step 2: Compute importance scores
    print("\n📊 Step 2: Computing importance scores...")
    scores = compute_importance_scores(files)

    # Step 3: Classify experts
    print("\n🏷️  Step 3: Classifying experts...")
    classification = classify_experts(scores, config)

    print(f"  Core experts:      {len(classification['core'])} → {config.core_quant}")
    print(f"  Standard experts:  {len(classification['standard'])} → {config.standard_quant}")
    print(f"  Peripheral experts: {len(classification['peripheral'])} → {config.peripheral_quant}")

    # Step 4: Generate quantization script
    print("\n📝 Step 4: Generating quantization script...")
    script = generate_quantization_script(classification, config)

    output_script = args.output_dir + "/quantize.sh"
    os.makedirs(args.output_dir, exist_ok=True)
    with open(output_script, 'w') as f:
        f.write(script)
    print(f"  Saved to {output_script}")

    # Step 5: Save classification report
    report = {
        "model": args.input_model,
        "calibration_files": len(files),
        "config": {
            "core_experts": config.core_experts,
            "core_quant": config.core_quant,
            "standard_quant": config.standard_quant,
            "peripheral_quant": config.peripheral_quant,
        },
        "classification": classification,
        "total_experts": sum(len(v) for v in classification.values()),
    }

    report_path = args.output_dir + "/quantization_report.json"
    with open(report_path, 'w') as f:
        json.dump(report, f, indent=2)
    print(f"  Report saved to {report_path}")

    print("\n✅ Quantization plan generated successfully.")
    print("\n📋 Next steps:")
    print("  1. Review the generated quantize.sh script")
    print("  2. Ensure llama.cpp is installed and compiled")
    print("  3. Run: bash quantize.sh")


def main():
    parser = argparse.ArgumentParser(
        description="🐉 LongShu Game Engine-Aware Hybrid Quantization Tool"
    )
    parser.add_argument('--input-model', type=str, required=True,
                        help='Path to the original model directory')
    parser.add_argument('--calibration-data', type=str, default='./calibration_corpus/',
                        help='Path to game development calibration data')
    parser.add_argument('--output-dir', type=str, default='./quantization_output/',
                        help='Output directory for quantization artifacts')

    args = parser.parse_args()
    run_quantization(args)


if __name__ == '__main__':
    main()
